# Drupal with Mariadb
#
# Access via "http://localhost:8080" (or "http://$(docker-machine ip):8080" if using docker-machine)

version: '2'

services:

  web1:
    build: web1
    volumes:
      - /vagrant/web1/www:/var/www/:rw
    ports:
      - 8081:80
    restart: always
    tty: true

  web2:
    build: web2
#drupal:7.53-apache
    volumes:
      - /vagrant/web2/www:/var/www:rw
    ports:
      - 8082:80
    restart: always
    tty: true

  web3:
    build: node1
    volumes:
      - /vagrant/node1/data:/home/app/data:rw
    links:
      - mongo
    ports:
      - "8083:80"
    tty: true

  mongo:
    build: mongo/3.4
    ports:
      - "27017:27017"
      - "28017:28017"
#    command: --break-mongo

  mariadb:
    image: mariadb:latest
    command: mysqld --innodb-buffer-pool-size=20M
    user: "1000"
    volumes:
      - "/vagrant/mariadb/db:/var/lib/mysql:rw"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    restart: always


